#!/bin/sh

cd "$HOME/dot" || exit

install_configs() {
    for i in $(find "$HOME"/dot -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sed 's|gentoo||g;s|.git||g')
    do
        stow -R "$i"
    done
}

install_programs() {
    # add installing portage var
    emerge -avt \
        "$(awk 'BEGIN {RS=""}{gsub(/\n/," ",$0); print $0}' "$HOME"/dot/gentoo/world)"
}

install_overlay() {
    emerge -avt app-eselect/eselect-repository

    eselect repository create kumao 

    while IFS= read -r repo; do
        eselect repository enable "$repo"
    done < "$HOME"/dot/gentoo/repositories

    cp -r "$HOME"/dot/gentoo/repo/* /var/db/repos/kumao/
}

remove_configs() {
    for i in $(find "$HOME"/dot -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sed 's|gentoo||g;s|.git||g')
    do
        stow -D "$i"
    done
}

remove_programs() {
    # add removing portage var
    emerge -aW \
        "$(awk 'BEGIN {RS=""}{gsub(/\n/," ",$0); print $0}' "$HOME"/dot/gentoo/world)" \
        --exclude app-eselect/eselect-repository && \
        emerge -cva
}

remove_overlay() {
    while IFS= read -r repo; do
        eselect repository remove "$repo"
    done < "$HOME"/dot/gentoo/repositories

    emerge -aW app-eselect/eselect-repository && emerge -cva
}

help() {
  printf "qdot: utility to install or remove my dotfiles\n\
  Options: -[ i,ic,ip,io,r,rc,rp,ro ]\n\
  	[ --install ] [ --remove ]\n\
	[ -configs ]  [ -overlay ] [ -programs ]\n"
}
case $1 in
    -i)
        install_configs
        install_overlay
        install_programs
        ;;
    -ic)
        install_configs
        ;;
    -ip)
        install_programs
        ;;
    -io)
        install_overlay
        ;;
    -r)
        remove_programs
        remove_overlay
        remove_configs
        ;;
    -rc)
        remove_configs
        ;;
    -rp)
        remove_programs
        ;;
    -ro)
        remove_overlay
        ;;
    -h)
        help
        ;;
    *)
        help
        ;;
esac
