#!/bin/sh
alias j='z'
alias f='zi'
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='$ZDOTDIR/zsh-lvim-padding ~/.config/nvim/'
alias vi='$ZDOTDIR/zsh-lvim-padding'
alias lvim='$ZDOTDIR/zsh-lvim-padding'
alias nvim='$ZDOTDIR/zsh-lvim-padding'

# alias lvim='nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim"'

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Remarkable
alias remarkable_ssh='ssh root@10.11.99.1'
alias restream='restream -p'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias rm='rm -i'
alias mv='mv -i'
alias ln='ln -i'
alias mkdir="mkdir -pv"

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

alias mach_java_mode="export SDKMAN_DIR="$HOME/.sdkman" && [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh""

alias m="git checkout master"
alias s="git checkout stable"

if [[ $TERM == "xterm-kitty" ]]; then
  alias ssh="kitty +kitten ssh"
fi

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac


# Define aliases
PRIV="$(command -v doas)"

alias c="clear"
alias :q="exit"
alias hd="hexdump -C"
alias ls="exa -lgh --group-directories-first"
alias la="exa -lgha --group-directories-first"

alias nvimsu="${PRIV} $ZDOTDIR/zsh-lvim-padding"
alias v='$ZDOTDIR/zsh-lvim-padding'
alias py="python"
alias clock="tty-clock"
alias qb="qutebrowser"
alias wstatus="iwctl station wlan0 show"
alias wifi="iwctl"

alias .1="cd .."
alias .2="cd ../.."
alias .3="cd ../../.."

alias p="$HOME/.config/polybar/launch"
alias k="kwal"
alias n="neofetch"
alias anime="ani-cli"
alias a="ani-cli"
alias manga="tachidesk"
alias m="tachidesk"

#alias emerge-sync="${PRIV} eix-sync"
#alias emerge-upgrade="${PRIV} emerge --update --newuse --deep --ask --tree --verbose --with-bdeps=y --quiet @world && ${PRIV} smart-live-rebuild"
#alias emerge-install="${PRIV} emerge -avtq"
#alias emerge-depclean="${PRIV} emerge -av --depclean"

#alias emerge_install="${PRIV} emerge -avt"
#alias emerge_install_unmask="${PRIV} emerge -avt --autounmask=y --autounmask-write"
#alias emerge_pretend="${PRIV} emerge -pv"
#alias emerge_sync="${PRIV} emaint -a sync"
#alias emerge_changed_use="${PRIV} emerge -avt --update --changed-use --deep @world"
#alias emerge_new_use="${PRIV} emerge -avt --update --newuse --deep @world"
#alias emerge_depclean="${PRIV} emerge -av --depclean"
#alias eclean_dist="${PRIV} eclean-dist --deep"
#alias eclean_pkg="${PRIV} eclean-pkg --deep"

alias rc-service="${PRIV} rc-service"
alias rc-update="${PRIV} rc-update"
alias clean_ram="${PRIV} sh -c 'sync; echo 3 > /proc/sys/vm/drop_caches'"
alias g="qupgrade"
alias u="qupgrade sync"
