#!/bin/sh
PRIV="$(command -v doas)"

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# lunarvim
alias nvimrc='$ZDOTDIR/zsh-lvim-padding ~/.config/nvim/'
alias vi='$ZDOTDIR/zsh-lvim-padding'
alias lvim='$ZDOTDIR/zsh-lvim-padding'
alias nvim='$ZDOTDIR/zsh-lvim-padding'
# alias lvim='nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim"'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias rm='rm -i'
alias mv='mv -i'
alias ln='ln -i'
alias mkdir="mkdir -pv"

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
# alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
# alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"
# For when keys break
# alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# alias m="git checkout master"
# alias s="git checkout stable"

# if [[ $TERM == "xterm-kitty" ]]; then
  # alias ssh="kitty +kitten ssh"
# fi

alias c="clear"
alias :q="exit"
alias hd="hexdump -C"
alias ls="exa -lgh --group-directories-first"
alias la="exa -lgha --group-directories-first"

alias nvimsu="${PRIV} /usr/bin/nvim"
alias v='$ZDOTDIR/zsh-lvim-padding'
alias py="python"
alias clock="tty-clock"
alias qb="qutebrowser"
alias wstatus="iwctl station wlan0 show"
alias wifi="iwctl"

alias .1="cd .."
alias .2="cd ../.."
alias .3="cd ../../.."

alias p="$HOME/.config/polybar/launch"
alias k="kwal"
alias n="neofetch"
alias ani-cli="clear && ani-cli"
alias ani="ani-cli"
alias anime="ani-cli"
alias manga-cli="clear && manga-cli"
alias manga="manga-cli"

alias emerge="${PRIV} emerge"
alias rc-service="${PRIV} rc-service"
alias rc-update="${PRIV} rc-update"
alias clean-ram="${PRIV} sh -c 'sync; echo 3 > /proc/sys/vm/drop_caches'"
alias eupgarde="qupgrade"
alias upgrade="qupgrade sync"
